spring.application.name=backend

# MyBatis XML 파일 위치 지정
mybatis.mapper-locations=classpath:mapper/**/*.xml

# MySQL 데이터베이스 연결 정보
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=${DB_CLASS}
#spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MyBatis 쿼리 로그 출력
logging.level.com.stocktracer.backend=debug

# snake와 camel 매핑
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.sql.init.mode=always

